import os
import json
import logging
from flask import Flask, request, jsonify, redirect
from flask_cors import CORS
import google.generativeai as genai
from dotenv import load_dotenv

# --- CONFIGURATION ---
load_dotenv()
app = Flask(__name__)

# Configure Logging
logging.basicConfig(level=logging.INFO)

# Allow CORS for app communication
CORS(app)

API_KEY = os.getenv("GEMINI_API_KEY")
if not API_KEY:
    logging.error("CRITICAL WARNING: GEMINI_API_KEY is missing from .env")
else:
    genai.configure(api_key=API_KEY)

# Transparency & Legal URLs
AI_DISCLOSURE = "AI Disclosure: This analysis is generated by Artificial Intelligence for educational purposes. It does not constitute psychological or legal advice."
PRIVACY_URL = "https://digitalabcs.com.au/privacy.html"
TERMS_URL = "https://digitalabcs.com.au/terms.html"

# System Instruction
SYSTEM_INSTRUCTION = """
You are an expert Linguistic Analyst providing multi-perspective communication analysis.
ANALYZE conversations for intents, communication styles, and interaction patterns.
DETECTION RULES: Use names if present, attribute every sentence, detect speaker changes via context.
ANALYTICAL FRAMEWORK: Emotional, Strategic, Relational, and Underlying Needs.
NO psychological diagnoses. Ground all observations in specific textual evidence.
"""

def generate_with_fallback(prompt, json_mode=True):
    try:
        model = genai.GenerativeModel(model_name='gemini-1.5-flash', system_instruction=SYSTEM_INSTRUCTION)
        response = model.generate_content(prompt, generation_config={"temperature": 0.4, "response_mime_type": "application/json"})
        data = json.loads(response.text)
        data["ai_disclosure"] = AI_DISCLOSURE
        return data
    except Exception as e:
        logging.error(f"Generation failed: {e}")
        return {"error": "SERVICE_UNAVAILABLE", "message": str(e)}

# --- ENDPOINTS ---

@app.route('/analyze', methods=['POST'])
def analyze():
    text = request.json.get('text', '')
    return jsonify(generate_with_fallback(f"Analyze: {text}"))

@app.route('/analyze-profile', methods=['POST'])
def analyze_profile():
    data = request.json
    name = data.get('name', 'Speaker')
    logs = data.get('logs', [])
    history = "\\n".join([f"[{l.get('date')}] {l.get('text')}" for l in logs[-15:]])
    return jsonify(generate_with_fallback(f"Analyze patterns for {name} using history: {history}"))

@app.route('/simulate', methods=['POST'])
def simulate():
    data = request.json
    context = data.get('context', '')
    draft = data.get('draft', '')
    prompt = f"Context: {context}\\nDraft: {draft}\\nAnalyze likely interpretation."
    return jsonify(generate_with_fallback(prompt))

@app.route('/identify-speakers', methods=['POST'])
def identify_speakers():
    text = request.json.get('text', '')
    return jsonify(generate_with_fallback(f"Identify speakers and attribute text for: {text}"))

@app.route('/privacy')
def privacy(): return redirect(PRIVACY_URL)

@app.route('/terms')
def terms(): return redirect(TERMS_URL)

@app.route('/health', methods=['GET'])
def health_check():
    return jsonify({"status": "healthy", "compliance": "Privacy Act 1988"}), 200

if __name__ == '__main__':
    port = int(os.getenv("PORT", 8080))
    app.run(debug=True, host='0.0.0.0', port=port)